spring.application.name=BooksManagement
server.port=8085
server.servlet.context-path=/api
#spring.datasource.url=jdbc:mysql://localhost:3306/books?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.generate-ddl=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.fmt-sql=true
#spring.datasource.testWhileIdle =true
#spring.datasource.validationQuery =SELECT 1
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect.type=InnoDB
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/books
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Optional - Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ReadMoreandStayFocusOnGoalsorThingsYouInLifeDIL
#jwt.secret=mySuperSecureJwtSecretKeyForProduction123456789
jwt.expiration=95000000

# Maximum size of a single uploaded file
spring.servlet.multipart.max-file-size=10MB
file.upload.path=/uploads/pdfs/

# Maximum size of the entire multipart request
spring.servlet.multipart.max-request-size=10MB


#gmail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your-email@gmail.com
#spring.mail.password=your-app-password
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000


#outlook
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=your-email@company.com
spring.mail.password=your-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Full path to the Piper Text-to-Speech executable.
# Spring Boot invokes this executable to generate speech audio from text.
tts.piper-path=C:/SoftwareSetup/piper_windows_amd64/piper/piper.exe

# Folder where all Piper voice models are stored.
# Each voice requires both a .onnx model file and its corresponding .onnx.json configuration file.
tts.model-directory=C:/SoftwareSetup/piper_windows_amd64/models

# Name of the default voice model to use.
# The service resolves the model path as:
# <tts.model.directory>/<tts.default.voice>.onnx
# Example:
# C:/SoftwareSetup/piper_windows_amd64/models/en_US-lessac-medium.onnx
tts.default-voice=en_US-lessac-medium
